[Service]
Environment=LD_LIBRARY_PATH=/home/radxa/qairt_2.42.0.251225/examples/Genie/Genie/build/lib:/home/radxa/qairt_2.42.0.251225/lib/aarch64-oe-linux-gcc11.2
Environment=ADSP_LIBRARY_PATH=/home/radxa/qairt_2.42.0.251225/lib/hexagon-v68/unsigned
